build:
  stage: build
  only:
  - tags
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  - docker pull shimaore/opensips:${DOCKER_OPENSIPS_VERSION}
  script:
  - docker build -t ${CI_REGISTRY_IMAGE}:${PROJECT_TAG} .
  - docker push ${CI_REGISTRY_IMAGE}:${PROJECT_TAG}

variables:
  PROJECT_TAG: "15.6.2"
  DOCKER_OPENSIPS_VERSION: "v4.2.3"
