image: gitlab.k-net.fr:1234/shimaore/ci-docker

build:
  stage: build
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  script:
  - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} .
  - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}

test:
  stage: test
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  - docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  script:
  - docker run --rm -e DEBUG="ccnq4-opensips:test:*" ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} npm test

deploy:
  stage: deploy
  before_script:
  - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
  - docker pull ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
  script:
  - if test "${CI_COMMIT_REF_NAME}" = master; then
      docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} ${CI_REGISTRY_IMAGE}:latest &&
      docker push ${CI_REGISTRY_IMAGE}:latest;
    fi
  - if test -n "${CI_COMMIT_TAG}"; then
      docker tag ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA} "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}" &&
      docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}";
    fi
